config/routes.rb
Closing20::Application.routes.draw do
  resources :total_closings

  root :to => "total_closings#index"
end

app/models/total_closing.rb
class TotalClosing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/total_closings_controller.rb
class TotalClosingsController < ApplicationController
  before_action :set_total_closing, only: [:show, :edit, :update, :destroy]

  # GET /total_closings
  # GET /total_closings.json
  def index
    @total_closings = TotalClosing.all
  end

  # GET /total_closings/1
  # GET /total_closings/1.json
  def show
  end

  # GET /total_closings/new
  def new
    @total_closing = TotalClosing.new
  end

  # GET /total_closings/1/edit
  def edit
  end

  # POST /total_closings
  # POST /total_closings.json
  def create
    @total_closing = TotalClosing.new(total_closing_params)

    respond_to do |format|
      if @total_closing.save
        format.html { redirect_to @total_closing, notice: 'Total closing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @total_closing }
      else
        format.html { render action: 'new' }
        format.json { render json: @total_closing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /total_closings/1
  # PATCH/PUT /total_closings/1.json
  def update
    respond_to do |format|
      if @total_closing.update(total_closing_params)
        format.html { redirect_to @total_closing, notice: 'Total closing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @total_closing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /total_closings/1
  # DELETE /total_closings/1.json
  def destroy
    @total_closing.destroy
    respond_to do |format|
      format.html { redirect_to total_closings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_total_closing
      @total_closing = TotalClosing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def total_closing_params
      params.require(:total_closing).permit(:Total_sale, :Total_pin, :Total_creditcard, :TMZ_Phone, :TMZ_Total, :Sunny_Phone, :Sunny_Total, :Raj, :Bill_paid, :Bill_Received, :Other_paid, :Other_amount, :Cash_In_Hand)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/total_closings_helper.rb
module TotalClosingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Closing20</title>
  <%= stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="/total_closings">Closing</a>
    <ul class="nav">
      

    </ul>
  </div>
</div>

<%= yield %>
</div>

</body>
</html>

app/views/total_closings/_form.html.erb
<%= form_for(@total_closing) do |f| %>
  <% if @total_closing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@total_closing.errors.count, "error") %> prohibited this total_closing from being saved:</h2>

      <ul>
      <% @total_closing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Total_sale %><br>
    <%= f.number_field :Total_sale %>
  </div>
  <div class="field">
    <%= f.label :Total_pin %><br>
    <%= f.number_field :Total_pin %>
  </div>
  <div class="field">
    <%= f.label :Total_creditcard %><br>
    <%= f.number_field :Total_creditcard %>
  </div>
  <div class="field">
    <%= f.label :TMZ_Phone %><br>
    <%= f.text_field :TMZ_Phone %>
  </div>
  <div class="field">
    <%= f.label :TMZ_Total %><br>
    <%= f.number_field :TMZ_Total %>
  </div>
  <div class="field">
    <%= f.label :Sunny_Phone %><br>
    <%= f.text_field :Sunny_Phone %>
  </div>
  <div class="field">
    <%= f.label :Sunny_Total %><br>
    <%= f.number_field :Sunny_Total %>
  </div>
  <div class="field">
    <%= f.label :Raj %><br>
    <%= f.number_field :Raj %>
  </div>
  <div class="field">
    <%= f.label :Bill_paid %><br>
    <%= f.number_field :Bill_paid %>
  </div>
  <div class="field">
    <%= f.label :Bill_Received %><br>
    <%= f.number_field :Bill_Received %>
  </div>
  <div class="field">
    <%= f.label :Other_paid %><br>
    <%= f.text_field :Other_paid %>
  </div>
  <div class="field">
    <%= f.label :Other_amount %><br>
    <%= f.number_field :Other_amount %>
  </div>
  <div class="field">
    <%= f.label :Cash_In_Hand %><br>
    <%= f.number_field :Cash_In_Hand %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => "btn btn-success" %>
  </div>
<% end %>

app/views/total_closings/edit.html.erb
<h1>Editing total_closing</h1>

<%= render 'form' %>

<%= link_to 'Show', @total_closing %> |
<%= link_to 'Back', total_closings_path %>

app/views/total_closings/index.html.erb
<h1>EVERY DAY CLOSINGS</h1>
<%= link_to 'New Total closing', new_total_closing_path, :class => "btn btn-danger" %>

<table class="table table-striped">
<thead>
  
    <tr>
      <th><span class="label label-success">Total sale</span></th>
      <th><span class="label label-success">Total pin</span></th>
      <th><span class="label label-success">Total creditcard</span></th>
      <th><span class="label label-success">Tmz phone</span></th>
      <th><span class="label label-success">Tmz total</span></th>
      <th><span class="label label-success">Sunny phone</span></th>
      <th><span class="label label-success">Sunny total</span></th>
      <th><span class="label label-success">Raj</span></th>
      <th><span class="label label-success">Bill paid</span></th>
      <th><span class="label label-success">Bill received</span></th>
      <th><span class="label label-success">Other paid</span></th>
      <th><span class="label label-success">Other amount</span></th>
      <th><span class="label label-success">Cash in hand</span></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @total_closings.each do |total_closing| %>
      <tr>
        
        <td><%= total_closing.Total_sale %></td>
        <td><%= total_closing.Total_pin %></td>
        <td><%= total_closing.Total_creditcard %></td>
        <td><%= total_closing.TMZ_Phone %></td>
        <td><%= total_closing.TMZ_Total %></td>
        <td><%= total_closing.Sunny_Phone %></td>
        <td><%= total_closing.Sunny_Total %></td>
        <td><%= total_closing.Raj %></td>
        <td><%= total_closing.Bill_paid %></td>
        <td><%= total_closing.Bill_Received %></td>
        <td><%= total_closing.Other_paid %></td>
        <td><%= total_closing.Other_amount %></td>
        <td><%= total_closing.Cash_In_Hand %></td>

        <td><%= link_to 'Show', total_closing %></td>
        <td><%= link_to 'Edit', edit_total_closing_path(total_closing) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/total_closings/new.html.erb
<div class="container">
  <div class="row" id="login-container">
    <div class="span8 offset2">
       <h1>ABC WIRELESS CLOSING</h1>

<%= render 'form' %>

<%= link_to 'Back', total_closings_path %>
    </div>
  </div>
</div>

app/views/total_closings/show.html.erb
<div class="container">
  <div class="row" id="login-container">
    <div class="span8 offset2">
<p id="notice"><%= notice %></p>

<p>
  <strong>Total sale:</strong>
  <%= @total_closing.Total_sale %>
</p>

<p>
  <strong>Total pin:</strong>
  <%= @total_closing.Total_pin %>
</p>

<p>
  <strong>Total creditcard:</strong>
  <%= @total_closing.Total_creditcard %>
</p>

<p>
  <strong>Tmz phone:</strong>
  <%= @total_closing.TMZ_Phone %>
</p>

<p>
  <strong>Tmz total:</strong>
  <%= @total_closing.TMZ_Total %>
</p>

<p>
  <strong>Sunny phone:</strong>
  <%= @total_closing.Sunny_Phone %>
</p>

<p>
  <strong>Sunny total:</strong>
  <%= @total_closing.Sunny_Total %>
</p>

<p>
  <strong>Raj:</strong>
  <%= @total_closing.Raj %>
</p>

<p>
  <strong>Bill paid:</strong>
  <%= @total_closing.Bill_paid %>
</p>

<p>
  <strong>Bill received:</strong>
  <%= @total_closing.Bill_Received %>
</p>

<p>
  <strong>Other paid:</strong>
  <%= @total_closing.Other_paid %>
</p>

<p>
  <strong>Other amount:</strong>
  <%= @total_closing.Other_amount %>
</p>

<p>
  <strong>Cash in hand:</strong>
  <%= @total_closing.Cash_In_Hand %>
</p>

<p>
  <span class="label label-important"><strong>TOTAL</strong>
  <%= @total_closing.Total_sale + @total_closing.Total_pin - @total_closing.Total_creditcard - @total_closing.TMZ_Total - @total_closing.Sunny_Total - @total_closing.Raj - @total_closing.Bill_paid + @total_closing.Bill_Received - @total_closing.Other_amount  %>


  </span>
</p>



<%= link_to 'Edit', edit_total_closing_path(@total_closing) %> |
<%= link_to 'Back', total_closings_path %>
</div>
</div>
</div>